import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/compnents/Theme/ThemeProvider";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

// 2. Configure Body Font
const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${jakarta.variable} ${inter.variable} h-full antialiased`}
      
    >
      <body className="min-h-full flex flex-col font-(family-name:--font-body) ">
        <ThemeProvider>
          {children}
          
        </ThemeProvider>
        </body>
    </html>
  );
}
